### ISSUE TITLE
HTML Game page

### ISSUE THREAD

**Issue by m0r1tz-lgr** [if-03-01-C-fall-2019/webapp-motor#1]
Add a extra page to the website where the users can play the game 
+ A good background (#2)
+ The game should be in the middle of the page (#11).
+ A box for the Score will be placed in (#7).
+ A box with short explanation about the game controls (#9) .

**Comment by haslingerm** [comment]
It would be a good idea to use English here just like anywhere else.
Also a description of the issue is needed - if I'd want to contribute I couldn't tell what 'allgemein anpassen' exactly means.

**Comment by m0r1tz-lgr** [comment]
Thank you for the feedback, if it is possible I would redo the issues and of Course add a description Gesendet von Mail für Windows 10 Von: MarkusGesendet: Donnerstag, 7. Mai 2020 10:53An: if-03-01-C-fall-2019/webapp-motorCc: moritz-c#; AuthorBetreff: Re: [if-03-01-C-fall-2019/webapp-motor] HTML und CSS allgemein anpassen (#1) It would be a good idea to use English here just like anywhere else.Also a description of the issue is needed - if I'd want to contribute I couldn't tell what 'allgemein anpassen' exactly means.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
